import jsPDF from "jspdf";
import { loadSnapsureLogo } from "@/lib/snapsure-logo";
import autoTable from "jspdf-autotable";
import { supabase } from "@/integrations/supabase/client";
import type { PdfBranding } from "@/lib/branding";

export interface HhPdfProperty {
  id: string;
  address: string;
  suburb: string;
  city: string;
  postcode: string;
  property_type: string;
}

export interface HhPdfInspection {
  id: string;
  property_id: string;
  inspection_date: string;
  inspector_name: string;
}

export interface HhPdfSignature {
  signer_role: "landlord" | "tenant";
  signer_name: string;
  signature_data: string;
  signed_at: string;
}

// Raw JSONB shapes from the assessment record (mirrors healthy-homes route).
type YesNo = "yes" | "no" | "";
type YesNoUnknown = "yes" | "no" | "unknown" | "";
type YesNoNA = "yes" | "no" | "na" | "";

export interface HhHeating {
  heater_type?: string;
  length_m?: number | "";
  width_m?: number | "";
  ceiling_m?: number | "";
  heater_capacity_kw?: number | "";
  photo_path?: string | null;
  notes?: string;
}
export interface HhInsulation {
  ceiling?: YesNoUnknown;
  ceiling_thickness_mm?: number | "";
  underfloor?: YesNoNA;
  underfloor_thickness_mm?: number | "";
  condition_ok?: YesNo;
  photo_ceiling_path?: string | null;
  photo_underfloor_path?: string | null;
  notes?: string;
}
export interface HhVentilation {
  rooms?: Record<string, YesNo>;
  kitchen_fan?: YesNo;
  kitchen_duct_mm?: number | "";
  bathroom_fan?: YesNo;
  bathroom_duct_mm?: number | "";
  photo_kitchen_path?: string | null;
  photo_bathroom_path?: string | null;
  notes?: string;
}
export interface HhMoisture {
  gutters_ok?: YesNo;
  water_ingress?: YesNo;
  subfloor?: YesNo;
  moisture_barrier?: YesNo;
  photo_gutters_path?: string | null;
  photo_moisture_path?: string | null;
  photo_subfloor_path?: string | null;
  notes?: string;
}
export interface HhDraught {
  gaps?: YesNo;
  gaps_description?: string;
  open_fireplace?: YesNo;
  fireplace_blocked?: YesNo;
  photo_gaps_path?: string | null;
  photo_fireplace_path?: string | null;
  notes?: string;
}
export interface HhSmoke {
  present?: YesNo;
  count?: number | "";
  near_bedrooms?: YesNo;
  tested?: YesNo;
  alarm_type?: string;
  photo_path?: string | null;
  notes?: string;
}

export type HhStatus = "green" | "amber" | "red" | "unknown";
export type HhOverall = "compliant" | "action_required" | "non_compliant";

export interface HhAssessment {
  heating_data: HhHeating | null;
  insulation_data: HhInsulation | null;
  ventilation_data: HhVentilation | null;
  moisture_data: HhMoisture | null;
  draught_data: HhDraught | null;
  smoke_alarms_data: HhSmoke | null;
  overall_status: string | null;
}

const TAGLINE = "Generated by Snapsure — snapsure.co.nz";
const STATUS_RGB: Record<HhStatus, [number, number, number]> = {
  green: [34, 139, 92],
  amber: [217, 155, 38],
  red: [200, 45, 45],
  unknown: [130, 130, 130],
};
const STATUS_LABEL: Record<HhStatus, string> = {
  green: "Meets standard",
  amber: "Action recommended",
  red: "Non-compliant",
  unknown: "Incomplete",
};
const OVERALL_LABEL: Record<HhOverall, string> = {
  compliant: "Compliant",
  action_required: "Action Required",
  non_compliant: "Non-Compliant",
};
const OVERALL_RGB: Record<HhOverall, [number, number, number]> = {
  compliant: [34, 139, 92],
  action_required: [217, 155, 38],
  non_compliant: [200, 45, 45],
};

const HEATER_LABEL: Record<string, string> = {
  heat_pump: "Heat pump",
  flued_gas: "Flued gas heater",
  wood_burner: "Wood burner",
  pellet_burner: "Pellet burner",
  fixed_electric: "Fixed electric heater",
  portable: "Portable/plug-in heater (non-compliant)",
  none: "No heater (non-compliant)",
  other: "Other",
};

const ALARM_LABEL: Record<string, string> = {
  photoelectric: "Photoelectric (recommended)",
  ionisation: "Ionisation",
  combined: "Combined photoelectric/ionisation",
  unknown: "Unknown",
};

function formatDMY(d: string) {
  const [y, m, day] = d.split("-");
  return `${day}/${m}/${y}`;
}

function capitalise(s: string) {
  if (!s) return "";
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function hhReportFilename(p: HhPdfProperty, i: HhPdfInspection) {
  const addr = (p.address || "property")
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, "_");
  return `Snapsure_${addr}_HealthyHomes_${i.inspection_date}.pdf`;
}

export function hhRefNumber(inspectionId: string) {
  const hex = inspectionId.replace(/-/g, "").slice(0, 8);
  const n = parseInt(hex, 16) % 100000;
  return `SNP-HH-${String(n).padStart(5, "0")}`;
}

// Status evaluators mirror the ones in inspection.$id.healthy-homes.tsx.
export function evalHeating(d: HhHeating | null): HhStatus {
  if (!d) return "unknown";
  const l = Number(d.length_m || 0);
  const w = Number(d.width_m || 0);
  const h = Number(d.ceiling_m || 2.4);
  const cap = Number(d.heater_capacity_kw || 0);
  const area = l > 0 && w > 0 ? l * w : null;
  const minKw = area != null ? area * h * 0.15 : null;
  if (d.heater_type === "portable" || d.heater_type === "none") return "red";
  if (!d.heater_type) return "unknown";
  if (minKw != null && cap > 0) return cap >= minKw ? "green" : "amber";
  return "unknown";
}
export function evalInsulation(d: HhInsulation | null): HhStatus {
  if (!d) return "unknown";
  if (d.ceiling === "no" || d.ceiling === "unknown") return "red";
  if (d.ceiling !== "yes") return "unknown";
  const ct = Number(d.ceiling_thickness_mm || 0);
  if (ct > 0 && ct < 120) return "amber";
  if (d.underfloor === "yes") {
    const ut = Number(d.underfloor_thickness_mm || 0);
    if (ut > 0 && ut < 120) return "amber";
  }
  if (d.condition_ok === "no") return "amber";
  return "green";
}
export function evalVentilation(d: HhVentilation | null): HhStatus {
  if (!d) return "unknown";
  const roomVals = Object.values(d.rooms ?? {});
  if (roomVals.some((v) => v === "no")) return "red";
  let amber = false;
  if (d.kitchen_fan === "yes") {
    const k = Number(d.kitchen_duct_mm || 0);
    if (k > 0 && k < 150) amber = true;
  }
  if (d.bathroom_fan === "yes") {
    const b = Number(d.bathroom_duct_mm || 0);
    if (b > 0 && b < 120) amber = true;
  }
  return amber ? "amber" : "green";
}
export function evalMoisture(d: HhMoisture | null): HhStatus {
  if (!d) return "unknown";
  if (d.water_ingress === "yes") return "red";
  if (d.gutters_ok === "no") return "amber";
  if (d.subfloor === "yes" && d.moisture_barrier === "no") return "amber";
  return "green";
}
export function evalDraught(d: HhDraught | null): HhStatus {
  if (!d) return "unknown";
  if (d.gaps === "yes") return "amber";
  if (d.open_fireplace === "yes" && d.fireplace_blocked === "no") return "amber";
  return "green";
}
export function evalSmoke(d: HhSmoke | null): HhStatus {
  if (!d) return "unknown";
  if (!d.present) return "unknown";
  if (d.present === "no") return "red";
  if (d.near_bedrooms === "no" || d.tested === "no") return "amber";
  if (!d.near_bedrooms || !d.tested) return "unknown";
  return "green";
}
export function evalOverall(statuses: HhStatus[]): HhOverall {
  if (statuses.some((s) => s === "red")) return "non_compliant";
  if (statuses.some((s) => s === "amber" || s === "unknown")) return "action_required";
  return "compliant";
}

async function fetchPhoto(path: string | null | undefined) {
  if (!path) return null;
  try {
    const { data, error } = await supabase.storage.from("inspection-photos").download(path);
    if (error || !data) return null;
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const fr = new FileReader();
      fr.onload = () => resolve(String(fr.result));
      fr.onerror = () => reject(fr.error);
      fr.readAsDataURL(data);
    });
    const dims = await new Promise<{ w: number; h: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ w: img.naturalWidth, h: img.naturalHeight });
      img.onerror = () => resolve({ w: 800, h: 600 });
      img.src = dataUrl;
    });
    return { dataUrl, w: dims.w, h: dims.h };
  } catch {
    return null;
  }
}

interface GenArgs {
  property: HhPdfProperty;
  inspection: HhPdfInspection;
  assessment: HhAssessment;
  signatures?: HhPdfSignature[];
  branding?: PdfBranding | null;
}

export async function generateHhReportPdf({
  property, inspection, assessment, signatures = [], branding = null,
}: GenArgs): Promise<Blob> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  const ref = hhRefNumber(inspection.id);
  const accent: [number, number, number] = branding?.accent ?? [15, 110, 86];
  const brandName = branding?.company_name ?? "Snapsure";
  const brandTagline = branding
    ? `Generated by ${brandName}`
    : TAGLINE;

  const statuses: HhStatus[] = [
    evalHeating(assessment.heating_data),
    evalInsulation(assessment.insulation_data),
    evalVentilation(assessment.ventilation_data),
    evalMoisture(assessment.moisture_data),
    evalDraught(assessment.draught_data),
    evalSmoke(assessment.smoke_alarms_data),
  ];
  const overall = evalOverall(statuses);

  // ---------- Cover page ----------
  let y = margin;
  if (branding?.logo) {
    try {
      const maxW = 45, maxH = 18;
      const ratio = branding.logo.w / branding.logo.h;
      let w = maxW, h = w / ratio;
      if (h > maxH) { h = maxH; w = h * ratio; }
      doc.addImage(branding.logo.dataUrl, "PNG", pageW - margin - w, y, w, h);
    } catch { /* skip */ }
  } else {
    const snap = await loadSnapsureLogo();
    if (snap) {
      try {
        const maxW = 28, maxH = 16;
        const ratio = snap.w / snap.h;
        let w = maxW, h = w / ratio;
        if (h > maxH) { h = maxH; w = h * ratio; }
        doc.addImage(snap.dataUrl, "PNG", pageW - margin - w, y, w, h);
      } catch { /* skip */ }
    }
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...accent);
  doc.text("Healthy Homes Compliance Assessment", margin, y + 4);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(brandTagline, margin, y + 4);
  y += 6;
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(`Report reference: ${ref}`, margin, y + 4);
  y += 14;

  const drawKV = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20);
    const lines = doc.splitTextToSize(value || "—", contentW - 45);
    doc.text(lines, margin + 45, y);
    y += 5 * (Array.isArray(lines) ? lines.length : 1) + 1;
  };

  const section = (title: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...accent);
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(...accent);
    doc.line(margin, y, pageW - margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);
  };

  section("Property");
  drawKV("Address", property.address);
  drawKV("Suburb", property.suburb);
  drawKV("City", property.city);
  drawKV("Postcode", property.postcode);
  drawKV("Type", capitalise(property.property_type));
  y += 4;

  section("Assessment");
  drawKV("Date", formatDMY(inspection.inspection_date));
  drawKV("Assessed by", inspection.inspector_name);
  y += 6;

  // Overall status pill
  const [or, og, ob] = OVERALL_RGB[overall];
  doc.setFillColor(or, og, ob);
  doc.roundedRect(margin, y, contentW, 14, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(255);
  doc.text(`Overall: ${OVERALL_LABEL[overall]}`, margin + 4, y + 9);
  y += 20;

  // Disclaimer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110);
  const disc = doc.splitTextToSize(
    "This is a self-assessment guide based on the Healthy Homes Standards (Residential Tenancies (Healthy Homes Standards) Regulations 2019). It does not constitute a professional compliance certificate. For certified compliance, engage a qualified assessor.",
    contentW,
  );
  doc.text(disc, margin, y);

  // ---------- Per-standard sections ----------
  const STANDARDS: { key: string; title: string; status: HhStatus; render: () => Promise<void> | void }[] = [
    {
      key: "heating",
      title: "1. Heating",
      status: statuses[0],
      render: async () => {
        const d = assessment.heating_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        const l = Number(d.length_m || 0);
        const w = Number(d.width_m || 0);
        const h = Number(d.ceiling_m || 2.4);
        const area = l > 0 && w > 0 ? l * w : null;
        const minKw = area != null ? area * h * 0.15 : null;
        const cap = Number(d.heater_capacity_kw || 0);
        drawTable([
          ["Heater type", d.heater_type ? HEATER_LABEL[d.heater_type] ?? d.heater_type : "—"],
          ["Room dimensions", area != null ? `${l} m × ${w} m (${area.toFixed(1)} m²)` : "—"],
          ["Ceiling height", d.ceiling_m ? `${d.ceiling_m} m` : "—"],
          ["Required minimum capacity", minKw != null ? `${minKw.toFixed(2)} kW` : "—"],
          ["Actual heater capacity", cap > 0 ? `${cap.toFixed(2)} kW` : "—"],
          ["Compliance", STATUS_LABEL[statuses[0]]],
        ]);
        await drawPhoto(d.photo_path, "Main living area heater");
        drawNotes(d.notes);
      },
    },
    {
      key: "insulation",
      title: "2. Insulation",
      status: statuses[1],
      render: async () => {
        const d = assessment.insulation_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        drawTable([
          ["Ceiling insulation", labelYNU(d.ceiling)],
          ["Ceiling thickness", d.ceiling_thickness_mm ? `${d.ceiling_thickness_mm} mm` : "—"],
          ["Underfloor insulation", labelYNNA(d.underfloor)],
          ["Underfloor thickness", d.underfloor_thickness_mm ? `${d.underfloor_thickness_mm} mm` : "—"],
          ["In good condition", labelYN(d.condition_ok)],
          ["Compliance", STATUS_LABEL[statuses[1]]],
        ]);
        await drawPhoto(d.photo_ceiling_path, "Ceiling insulation");
        await drawPhoto(d.photo_underfloor_path, "Underfloor insulation");
        drawNotes(d.notes);
      },
    },
    {
      key: "ventilation",
      title: "3. Ventilation",
      status: statuses[2],
      render: async () => {
        const d = assessment.ventilation_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        const rows: [string, string][] = [];
        const roomEntries = Object.entries(d.rooms ?? {});
        if (roomEntries.length > 0) {
          const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
          const uuidIds = roomEntries.map(([rid]) => rid).filter((rid) => uuidRe.test(rid));
          const nameMap = new Map<string, string>();
          if (uuidIds.length > 0) {
            const { data: roomRows } = await supabase
              .from("rooms")
              .select("id,name")
              .in("id", uuidIds);
            for (const r of roomRows ?? []) {
              if (r?.id && r?.name) nameMap.set(r.id as string, r.name as string);
            }
          }
          for (const [rid, v] of roomEntries) {
            const label = nameMap.get(rid) ?? (uuidRe.test(rid) ? "Unknown room" : rid);
            rows.push([`Window openable — ${label}`, labelYN(v as YesNo)]);
          }
        }
        rows.push(
          ["Kitchen extractor fan", labelYN(d.kitchen_fan)],
          ["Kitchen duct diameter", d.kitchen_duct_mm ? `${d.kitchen_duct_mm} mm` : "—"],
          ["Bathroom extractor fan", labelYN(d.bathroom_fan)],
          ["Bathroom duct diameter", d.bathroom_duct_mm ? `${d.bathroom_duct_mm} mm` : "—"],
          ["Compliance", STATUS_LABEL[statuses[2]]],
        );
        drawTable(rows);
        await drawPhoto(d.photo_kitchen_path, "Kitchen extractor");
        await drawPhoto(d.photo_bathroom_path, "Bathroom extractor");
        drawNotes(d.notes);
      },
    },
    {
      key: "moisture",
      title: "4. Moisture & Drainage",
      status: statuses[3],
      render: async () => {
        const d = assessment.moisture_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        drawTable([
          ["Gutters and downpipes clear", labelYN(d.gutters_ok)],
          ["Signs of water ingress", labelYN(d.water_ingress)],
          ["Enclosed subfloor space", labelYN(d.subfloor)],
          ["Ground moisture barrier", labelYN(d.moisture_barrier)],
          ["Compliance", STATUS_LABEL[statuses[3]]],
        ]);
        await drawPhoto(d.photo_gutters_path, "Gutters");
        await drawPhoto(d.photo_moisture_path, "Moisture areas");
        await drawPhoto(d.photo_subfloor_path, "Subfloor");
        drawNotes(d.notes);
      },
    },
    {
      key: "draught",
      title: "5. Draught Stopping",
      status: statuses[4],
      render: async () => {
        const d = assessment.draught_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        drawTable([
          ["Unreasonable gaps or holes", labelYN(d.gaps)],
          ["Gap details", d.gaps_description || "—"],
          ["Open fireplace present", labelYN(d.open_fireplace)],
          ["Fireplace blocked or sealed", labelYN(d.fireplace_blocked)],
          ["Compliance", STATUS_LABEL[statuses[4]]],
        ]);
        await drawPhoto(d.photo_gaps_path, "Gaps");
        await drawPhoto(d.photo_fireplace_path, "Fireplace");
        drawNotes(d.notes);
      },
    },
    {
      key: "smoke",
      title: "6. Smoke Alarms",
      status: statuses[5],
      render: async () => {
        const d = assessment.smoke_alarms_data;
        if (!d) {
          drawParagraph("No data recorded.");
          return;
        }
        drawTable([
          ["Working smoke alarms installed", labelYN(d.present)],
          ["Number of alarms", d.count ? String(d.count) : "—"],
          ["Installed near each bedroom", labelYN(d.near_bedrooms)],
          ["Tested", labelYN(d.tested)],
          ["Alarm type", d.alarm_type ? ALARM_LABEL[d.alarm_type] ?? d.alarm_type : "—"],
          ["Compliance", STATUS_LABEL[statuses[5]]],
        ]);
        await drawPhoto(d.photo_path, "Smoke alarm");
        drawNotes(d.notes);
      },
    },
  ];

  function labelYN(v: YesNo | undefined) {
    if (v === "yes") return "Yes";
    if (v === "no") return "No";
    return "—";
  }
  function labelYNU(v: YesNoUnknown | undefined) {
    if (v === "yes") return "Yes";
    if (v === "no") return "No";
    if (v === "unknown") return "Unknown";
    return "—";
  }
  function labelYNNA(v: YesNoNA | undefined) {
    if (v === "yes") return "Yes";
    if (v === "no") return "No";
    if (v === "na") return "Not applicable";
    return "—";
  }

  function drawStatusPill(status: HhStatus, x: number, yy: number) {
    const [r, g, b] = STATUS_RGB[status];
    doc.setFillColor(r, g, b);
    const label =
      status === "green" ? "✓ Compliant"
      : status === "amber" ? "! Action"
      : status === "red" ? "✗ Non-compliant"
      : "? Incomplete";
    const w = doc.getTextWidth(label) + 6;
    doc.roundedRect(x, yy - 5, w, 7, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(255);
    doc.text(label, x + 3, yy);
    return w;
  }

  function drawTable(rows: [string, string][]) {
    autoTable(doc, {
      startY: y,
      body: rows,
      margin: { left: margin, right: margin },
      styles: { font: "helvetica", fontSize: 10, cellPadding: 2.5, textColor: 30, valign: "top" },
      alternateRowStyles: { fillColor: [246, 246, 246] },
      columnStyles: {
        0: { cellWidth: 60, fontStyle: "bold", textColor: 90 },
        1: { cellWidth: "auto" },
      },
      theme: "plain",
    });
    // @ts-expect-error autoTable augments doc
    y = doc.lastAutoTable.finalY + 4;
  }

  function drawParagraph(text: string) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(50);
    const lines = doc.splitTextToSize(text, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 3;
  }

  function drawNotes(notes: string | undefined) {
    if (!notes || !notes.trim()) return;
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text("Notes", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30);
    const lines = doc.splitTextToSize(notes, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 3;
  }

  const MAX_PHOTO_MM = 70;
  async function drawPhoto(path: string | null | undefined, caption: string) {
    if (!path) return;
    const img = await fetchPhoto(path);
    if (!img) return;
    const ratio = img.w / img.h;
    let w = Math.min(contentW, 90);
    let h = w / ratio;
    if (h > MAX_PHOTO_MM) { h = MAX_PHOTO_MM; w = h * ratio; }
    ensureSpace(h + 8);
    try {
      doc.addImage(img.dataUrl, "JPEG", margin, y, w, h, undefined, "FAST");
    } catch {
      try { doc.addImage(img.dataUrl, "PNG", margin, y, w, h); } catch { return; }
    }
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(caption, margin, y + h + 4);
    y += h + 8;
  }

  function ensureSpace(needed: number) {
    if (y + needed > pageH - 25) {
      doc.addPage();
      y = margin;
    }
  }

  for (const std of STANDARDS) {
    doc.addPage();
    y = margin;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...accent);
    doc.text(std.title, margin, y + 2);
    const titleWidth = doc.getTextWidth(std.title);
    drawStatusPill(std.status, margin + titleWidth + 6, y);
    y += 6;
    doc.setDrawColor(...accent);
    doc.line(margin, y, pageW - margin, y);
    y += 6;
    await std.render();
  }

  // ---------- Final page: summary + signature ----------
  doc.addPage();
  y = margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...accent);
  doc.text("Summary", margin, y + 2);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [["Standard", "Status"]],
    body: STANDARDS.map((s) => [s.title.replace(/^\d+\.\s*/, ""), STATUS_LABEL[s.status]]),
    margin: { left: margin, right: margin },
    styles: { font: "helvetica", fontSize: 10, cellPadding: 2.5, valign: "top" },
    headStyles: { fillColor: accent, textColor: 255 },
    alternateRowStyles: { fillColor: [246, 246, 246] },
    columnStyles: {
      0: { cellWidth: "auto", fontStyle: "bold" },
      1: { cellWidth: 55 },
    },
    theme: "grid",
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 1) {
        const st = STANDARDS[data.row.index].status;
        data.cell.styles.textColor = STATUS_RGB[st];
        data.cell.styles.fontStyle = "bold";
      }
    },
  });
  // @ts-expect-error autoTable augments doc
  y = doc.lastAutoTable.finalY + 6;

  // Overall
  const [ovr, ovg, ovb] = OVERALL_RGB[overall];
  doc.setFillColor(ovr, ovg, ovb);
  doc.roundedRect(margin, y, contentW, 12, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(255);
  doc.text(`Overall: ${OVERALL_LABEL[overall]}`, margin + 4, y + 8);
  y += 18;

  // Signature block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...accent);
  doc.text("Assessor signature", margin, y);
  y += 8;

  const sig = signatures.find((s) => s.signer_role === "landlord") ?? signatures[0];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(60);
  doc.setDrawColor(180);

  doc.text("Name", margin, y);
  if (sig) {
    doc.setTextColor(20);
    doc.text(sig.signer_name, margin + 25, y);
    doc.setTextColor(60);
  } else {
    doc.setTextColor(20);
    doc.text(inspection.inspector_name, margin + 25, y);
    doc.setTextColor(60);
  }
  doc.line(margin + 25, y + 1, pageW - margin, y + 1);
  y += 12;

  doc.text("Signature", margin, y);
  if (sig?.signature_data) {
    try {
      doc.addImage(sig.signature_data, "PNG", margin + 25, y - 10, 60, 14);
    } catch { /* skip */ }
  }
  doc.line(margin + 25, y + 1, pageW - margin, y + 1);
  y += 12;

  doc.text("Date & time", margin, y);
  doc.setTextColor(20);
  const stampDate = sig ? new Date(sig.signed_at) : new Date();
  const stamp = `${String(stampDate.getDate()).padStart(2, "0")}/${String(stampDate.getMonth() + 1).padStart(2, "0")}/${stampDate.getFullYear()}, ${String(stampDate.getHours()).padStart(2, "0")}:${String(stampDate.getMinutes()).padStart(2, "0")}:${String(stampDate.getSeconds()).padStart(2, "0")}`;
  doc.text(stamp, margin + 25, y);
  doc.setTextColor(60);
  doc.line(margin + 25, y + 1, pageW - margin, y + 1);
  y += 14;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(110);
  const disc2 = doc.splitTextToSize(
    "Records and documents demonstrating compliance must be retained and made available to tenants on request within 21 days (Residential Tenancies Act 1986).",
    contentW,
  );
  doc.text(disc2, margin, y);

  // ---------- Footer on all pages ----------
  const totalPages = doc.getNumberOfPages();
  const shortAddr = property.address.length > 48
    ? property.address.slice(0, 45) + "…"
    : property.address;
  const contactBits = branding
    ? [branding.phone, branding.email, branding.address].filter(Boolean).join(" · ")
    : "";
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setDrawColor(220);
    if (branding) {
      doc.line(margin, pageH - 20, pageW - margin, pageH - 20);
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(ref, margin, pageH - 15);
      doc.text(shortAddr, pageW / 2, pageH - 15, { align: "center" });
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 15, { align: "right" });
      doc.setFontSize(7);
      doc.setTextColor(130);
      if (contactBits) {
        const lines = doc.splitTextToSize(contactBits, contentW - 30);
        doc.text(Array.isArray(lines) ? lines[0] : lines, margin, pageH - 11);
      }
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(brandName, margin, pageH - 7);
      doc.text(formatDMY(inspection.inspection_date), pageW - margin, pageH - 7, { align: "right" });
      doc.setFontSize(6.5);
      doc.setTextColor(180);
      doc.text(TAGLINE, pageW / 2, pageH - 4, { align: "center" });
    } else {
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.line(margin, pageH - 16, pageW - margin, pageH - 16);
      doc.text(ref, margin, pageH - 11);
      doc.text(shortAddr, pageW / 2, pageH - 11, { align: "center" });
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 11, { align: "right" });
      doc.setTextColor(150);
      doc.text(TAGLINE, margin, pageH - 7);
      doc.text(formatDMY(inspection.inspection_date), pageW - margin, pageH - 7, { align: "right" });
    }
  }

  return doc.output("blob");
}