import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/integrations/supabase/client";
import type { Condition } from "@/lib/parse-transcript";
import type { PdfBranding } from "@/lib/branding";

export interface PdfProperty {
  id: string; address: string; suburb: string; city: string; postcode: string;
  property_type: string; bedrooms: number; bathrooms: number;
}
export interface PdfInspection {
  id: string; property_id: string; inspection_type: "entry" | "routine" | "exit";
  inspection_date: string; inspector_name: string; tenant_names: string | null;
}
export interface PdfRoom { id: string; name: string; sort_order: number }
export interface PdfItem {
  id: string; room_id: string; item_name: string; condition: Condition;
  description: string | null; maintenance_required: boolean;
  maintenance_notes: string | null; sort_order: number;
}
export interface PdfPhoto { id: string; room_id: string; photo_url: string; captured_at: string }
export interface PdfSignature {
  signer_role: "landlord" | "tenant";
  signer_name: string;
  signature_data: string;
  signed_at: string;
}

const COND_RGB: Record<Condition, [number, number, number]> = {
  good: [34, 139, 92],     // green
  fair: [217, 155, 38],    // amber
  poor: [217, 108, 38],    // orange
  damaged: [200, 45, 45],  // red
};
const COND_LABEL: Record<Condition, string> = {
  good: "Good", fair: "Fair", poor: "Poor", damaged: "Damaged",
};
const COND_PRIORITY: Record<Condition, string> = {
  damaged: "High", poor: "Medium", fair: "Low", good: "Low",
};
const PROPERTY_TYPE_LABEL: Record<string, string> = {
  house: "House", apartment: "Apartment", unit: "Unit", townhouse: "Townhouse",
};
const INSPECTION_TYPE_LABEL: Record<string, string> = {
  entry: "Entry Inspection",
  routine: "Routine Inspection",
  exit: "Exit Inspection",
};
const TAGLINE = "Generated by Snapsure — snapsure.co.nz";

function capitalise(s: string) {
  if (!s) return "";
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function formatDMY(d: string) {
  const [y, m, day] = d.split("-");
  return `${day}/${m}/${y}`;
}

export function refNumber(inspectionId: string) {
  const hex = inspectionId.replace(/-/g, "").slice(0, 8);
  const n = parseInt(hex, 16) % 100000;
  return `SNP-2026-${String(n).padStart(5, "0")}`;
}

export function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function reportFilename(property: PdfProperty, inspection: PdfInspection) {
  const addr = (property.address || "property")
    .trim()
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .replace(/\s+/g, "_");
  const type = capitalise(inspection.inspection_type);
  return `Snapsure_${addr}_${type}_${inspection.inspection_date}.pdf`;
}

async function fetchPhotoDataUrl(path: string) {
  try {
    const { data, error } = await supabase.storage.from("inspection-photos").download(path);
    if (error || !data) return null;
    const dataUrl = await new Promise<string>((resolve, reject) => {
      const fr = new FileReader();
      fr.onload = () => resolve(String(fr.result));
      fr.onerror = () => reject(fr.error);
      fr.readAsDataURL(data);
    });
    const dims = await new Promise<{ w: number; h: number }>((resolve) => {
      const img = new Image();
      img.onload = () => resolve({ w: img.naturalWidth, h: img.naturalHeight });
      img.onerror = () => resolve({ w: 800, h: 600 });
      img.src = dataUrl;
    });
    return { dataUrl, w: dims.w, h: dims.h };
  } catch {
    return null;
  }
}

export interface GenerateReportArgs {
  inspection: PdfInspection;
  property: PdfProperty;
  rooms: PdfRoom[];
  items: PdfItem[];
  photos: PdfPhoto[];
  signatures?: PdfSignature[];
  branding?: PdfBranding | null;
}

export async function generateReportPdf({
  inspection, property, rooms, items, photos, signatures = [], branding = null,
}: GenerateReportArgs): Promise<Blob> {
  const ref = refNumber(inspection.id);

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;

  const accent: [number, number, number] = branding?.accent ?? [15, 110, 86];
  const brandName = branding?.company_name ?? "Snapsure";
  const brandTagline = branding
    ? `Generated by ${brandName}`
    : "Generated by Snapsure — snapsure.co.nz";

  // ---------- Cover page ----------
  let y = margin;
  // Optional company logo top-right on cover
  if (branding?.logo) {
    try {
      const maxW = 45;
      const maxH = 18;
      const ratio = branding.logo.w / branding.logo.h;
      let w = maxW;
      let h = w / ratio;
      if (h > maxH) { h = maxH; w = h * ratio; }
      doc.addImage(branding.logo.dataUrl, "PNG", pageW - margin - w, y, w, h);
    } catch { /* skip */ }
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...accent);
  doc.text("Property Inspection Report", margin, y + 4);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(brandTagline, margin, y + 4);
  y += 6;
  doc.setFontSize(10);
  doc.setTextColor(80);
  doc.text(`Report reference: ${ref}`, margin, y + 4);
  y += 12;

  const section = (title: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...accent);
    doc.text(title, margin, y);
    y += 2;
    doc.setDrawColor(...accent);
    doc.line(margin, y, pageW - margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);
  };

  const kv = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(90);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20);
    const lines = doc.splitTextToSize(value || "—", contentW - 45);
    doc.text(lines, margin + 45, y);
    y += 5 * (Array.isArray(lines) ? lines.length : 1) + 1;
  };

  section("Property Details");
  kv("Address", property.address);
  kv("Suburb", property.suburb);
  kv("City", property.city);
  kv("Postcode", property.postcode);
  kv("Property type", PROPERTY_TYPE_LABEL[property.property_type] ?? capitalise(property.property_type));
  kv("Bedrooms / Bathrooms", `${property.bedrooms} bed · ${property.bathrooms} bath`);
  y += 4;

  section("Inspection Details");
  kv("Inspection type", INSPECTION_TYPE_LABEL[inspection.inspection_type] ?? capitalise(inspection.inspection_type));
  kv("Date", formatDMY(inspection.inspection_date));
  kv("Inspector", inspection.inspector_name);
  kv("Tenant(s)", inspection.tenant_names || "—");
  y += 4;

  section("Condition Summary");
  const counts: Record<Condition, number> = { good: 0, fair: 0, poor: 0, damaged: 0 };
  for (const it of items) if (counts[it.condition] !== undefined) counts[it.condition]++;
  const conds: Condition[] = ["good", "fair", "poor", "damaged"];
  const boxW = (contentW - 9) / 4;
  const boxH = 20;
  conds.forEach((c, i) => {
    const x = margin + i * (boxW + 3);
    const [r, g, b] = COND_RGB[c];
    doc.setFillColor(r, g, b);
    doc.rect(x, y, boxW, boxH, "F");
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(String(counts[c]), x + boxW / 2, y + 9, { align: "center" });
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(COND_LABEL[c], x + boxW / 2, y + 15, { align: "center" });
  });
  y += boxH + 8;

  const roomsById = new Map(rooms.map((r) => [r.id, r]));

  const itemsByRoom = new Map<string, PdfItem[]>();
  for (const it of items) {
    const arr = itemsByRoom.get(it.room_id) ?? [];
    arr.push(it); itemsByRoom.set(it.room_id, arr);
  }
  const photosByRoom = new Map<string, PdfPhoto[]>();
  for (const p of photos) {
    const arr = photosByRoom.get(p.room_id) ?? [];
    arr.push(p); photosByRoom.set(p.room_id, arr);
  }

  // ---------- Room sections ----------
  // Max photo height 200 points = ~70.56 mm
  const MAX_PHOTO_MM = 200 * 0.352778;
  const roomsWithItems = rooms.filter((r) => (itemsByRoom.get(r.id)?.length ?? 0) > 0);
  for (const room of roomsWithItems) {
    const rItems = itemsByRoom.get(room.id) ?? [];
    const rPhotos = photosByRoom.get(room.id) ?? [];

    doc.addPage();
    y = margin;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...accent);
    doc.text(room.name, margin, y + 2);
    y += 8;

    // First photo at top of room, scaled to page width, max 200pt height
    if (rPhotos.length > 0) {
      const img = await fetchPhotoDataUrl(rPhotos[0].photo_url);
      if (img) {
        const ratio = img.w / img.h;
        let w = contentW;
        let h = w / ratio;
        if (h > MAX_PHOTO_MM) { h = MAX_PHOTO_MM; w = h * ratio; }
        try {
          doc.addImage(img.dataUrl, "JPEG", margin, y, w, h, undefined, "FAST");
        } catch {
          try { doc.addImage(img.dataUrl, "PNG", margin, y, w, h); } catch { /* skip */ }
        }
        y += h + 6;
      }
    }

    autoTable(doc, {
        startY: y,
        head: [["Item", "Condition", "Description", "Maintenance Required"]],
        body: rItems.map((it) => [
          it.item_name,
          COND_LABEL[it.condition] ?? String(it.condition ?? "—"),
          it.description ?? "",
          it.maintenance_required ? "Yes" : "No",
        ]),
        margin: { left: margin, right: margin },
        styles: { font: "helvetica", fontSize: 10, cellPadding: 2.5, textColor: 30, valign: "top" },
        headStyles: { fillColor: accent, textColor: 255 },
        alternateRowStyles: { fillColor: [246, 246, 246] },
        columnStyles: {
          0: { cellWidth: 35, fontStyle: "bold" },
          1: { cellWidth: 24, fontStyle: "bold" },
          2: { cellWidth: "auto" },
          3: { cellWidth: 32, halign: "center" },
        },
        theme: "grid",
        didParseCell: (data) => {
          if (data.section !== "body") return;
          const it = rItems[data.row.index];
          if (data.section === "body" && data.column.index === 1) {
            const cond = it?.condition as Condition;
            if (cond && COND_RGB[cond]) data.cell.styles.textColor = COND_RGB[cond];
          }
          if (data.column.index === 3 && it?.maintenance_required) {
            data.cell.styles.textColor = COND_RGB.damaged;
            data.cell.styles.fontStyle = "bold";
          }
        },
    });
    // @ts-expect-error autoTable augments doc
    y = doc.lastAutoTable.finalY + 6;
  }

  // ---------- Maintenance summary page ----------
  const maintenance = items.filter((i) => i.maintenance_required);
  doc.addPage();
  y = margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...accent);
  doc.text("Maintenance Summary", margin, y + 2);
  y += 10;
  if (maintenance.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(140);
    doc.text("No maintenance items reported.", margin, y);
    y += 8;
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Room", "Item", "Issue", "Priority"]],
      body: maintenance.map((m) => [
        roomsById.get(m.room_id)?.name ?? "",
        m.item_name,
        m.maintenance_notes || m.description || "—",
        COND_PRIORITY[m.condition] ?? "Low",
      ]),
      margin: { left: margin, right: margin },
      styles: { font: "helvetica", fontSize: 10, cellPadding: 2.5, textColor: 30, valign: "top" },
      headStyles: { fillColor: accent, textColor: 255 },
      alternateRowStyles: { fillColor: [246, 246, 246] },
      columnStyles: {
        0: { cellWidth: 32 },
        1: { cellWidth: 35, fontStyle: "bold" },
        2: { cellWidth: "auto" },
        3: { cellWidth: 22, halign: "center", fontStyle: "bold" },
      },
      theme: "grid",
      didParseCell: (data) => {
        if (data.section === "body" && data.column.index === 3) {
          const cond = maintenance[data.row.index]?.condition as Condition;
          if (cond && COND_RGB[cond]) data.cell.styles.textColor = COND_RGB[cond];
        }
      },
    });
  }

  // ---------- Signature page ----------
  doc.addPage();
  y = margin;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...accent);
  doc.text("Signatures", margin, y);
  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(30);
  const intro = "This property inspection report has been completed by the parties listed below. Both parties confirm that the report accurately reflects the condition of the property at the time of inspection.";
  const introLines = doc.splitTextToSize(intro, contentW);
  doc.text(introLines, margin, y);
  y += introLines.length * 5 + 10;

  const sigByRole = new Map(signatures.map((s) => [s.signer_role, s]));

  const drawSigBlock = (label: string, role: "landlord" | "tenant", startY: number) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...accent);
    doc.text(label, margin, startY);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60);
    doc.setDrawColor(180);

    const sig = sigByRole.get(role);
    let yy = startY + 8;

    // Name
    doc.text("Name", margin, yy);
    if (sig) {
      doc.setTextColor(20);
      doc.text(sig.signer_name, margin + 25, yy);
      doc.setTextColor(60);
    }
    doc.line(margin + 25, yy + 1, pageW - margin, yy + 1);
    yy += 12;

    // Signature
    doc.text("Signature", margin, yy);
    if (sig?.signature_data) {
      try {
        doc.addImage(sig.signature_data, "PNG", margin + 25, yy - 10, 60, 14);
      } catch { /* skip */ }
    }
    doc.line(margin + 25, yy + 1, pageW - margin, yy + 1);
    yy += 12;

    // Date
    doc.text("Date", margin, yy);
    if (sig) {
      doc.setTextColor(20);
      const d = new Date(sig.signed_at);
      doc.text(d.toLocaleString(), margin + 25, yy);
      doc.setTextColor(60);
    }
    doc.line(margin + 25, yy + 1, pageW - margin, yy + 1);
    yy += 12;

    return yy;
  };

  const afterLandlord = drawSigBlock("Landlord / Agent", "landlord", y);
  drawSigBlock("Tenant", "tenant", afterLandlord + 8);

  // ---------- Footer on all pages ----------
  const totalPages = doc.getNumberOfPages();
  const shortAddr = property.address.length > 48
    ? property.address.slice(0, 45) + "…"
    : property.address;
  const contactBits = branding
    ? [branding.phone, branding.email, branding.address].filter(Boolean).join(" · ")
    : "";
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setDrawColor(220);
    if (branding) {
      doc.line(margin, pageH - 20, pageW - margin, pageH - 20);
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text(ref, margin, pageH - 15);
      doc.text(shortAddr, pageW / 2, pageH - 15, { align: "center" });
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 15, { align: "right" });
      doc.setFontSize(7);
      doc.setTextColor(130);
      if (contactBits) {
        const lines = doc.splitTextToSize(contactBits, contentW - 30);
        doc.text(Array.isArray(lines) ? lines[0] : lines, margin, pageH - 11);
      }
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(brandName, margin, pageH - 7);
      doc.text(formatDMY(inspection.inspection_date), pageW - margin, pageH - 7, { align: "right" });
      doc.setFontSize(6.5);
      doc.setTextColor(180);
      doc.text("Powered by Snapsure", pageW / 2, pageH - 4, { align: "center" });
    } else {
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.line(margin, pageH - 16, pageW - margin, pageH - 16);
      doc.text(ref, margin, pageH - 11);
      doc.text(shortAddr, pageW / 2, pageH - 11, { align: "center" });
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 11, { align: "right" });
      doc.setTextColor(150);
      doc.text(TAGLINE, margin, pageH - 7);
      doc.text(formatDMY(inspection.inspection_date), pageW - margin, pageH - 7, { align: "right" });
    }
  }

  return doc.output("blob");
}