/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as AuthenticatedPropertyNewRouteImport } from './routes/_authenticated/property.new'
import { Route as AuthenticatedPropertyIdRouteImport } from './routes/_authenticated/property.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedInspectionSetupPropertyIdRouteImport } from './routes/_authenticated/inspection.setup.$propertyId'
import { Route as AuthenticatedInspectionIdSignRouteImport } from './routes/_authenticated/inspection.$id.sign'
import { Route as AuthenticatedInspectionIdReviewRouteImport } from './routes/_authenticated/inspection.$id.review'
import { Route as AuthenticatedInspectionIdReportRouteImport } from './routes/_authenticated/inspection.$id.report'
import { Route as AuthenticatedInspectionIdCompareRouteImport } from './routes/_authenticated/inspection.$id.compare'
import { Route as AuthenticatedInspectionIdCaptureRouteImport } from './routes/_authenticated/inspection.$id.capture'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertyNewRoute =
  AuthenticatedPropertyNewRouteImport.update({
    id: '/property/new',
    path: '/property/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertyIdRoute = AuthenticatedPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInspectionSetupPropertyIdRoute =
  AuthenticatedInspectionSetupPropertyIdRouteImport.update({
    id: '/inspection/setup/$propertyId',
    path: '/inspection/setup/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdSignRoute =
  AuthenticatedInspectionIdSignRouteImport.update({
    id: '/inspection/$id/sign',
    path: '/inspection/$id/sign',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdReviewRoute =
  AuthenticatedInspectionIdReviewRouteImport.update({
    id: '/inspection/$id/review',
    path: '/inspection/$id/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdReportRoute =
  AuthenticatedInspectionIdReportRouteImport.update({
    id: '/inspection/$id/report',
    path: '/inspection/$id/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdCompareRoute =
  AuthenticatedInspectionIdCompareRouteImport.update({
    id: '/inspection/$id/compare',
    path: '/inspection/$id/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdCaptureRoute =
  AuthenticatedInspectionIdCaptureRouteImport.update({
    id: '/inspection/$id/capture',
    path: '/inspection/$id/capture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/property/$id': typeof AuthenticatedPropertyIdRoute
  '/_authenticated/property/new': typeof AuthenticatedPropertyNewRoute
  '/_authenticated/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/_authenticated/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/_authenticated/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/_authenticated/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/_authenticated/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/_authenticated/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inspections'
    | '/settings'
    | '/property/$id'
    | '/property/new'
    | '/inspection/$id/capture'
    | '/inspection/$id/compare'
    | '/inspection/$id/report'
    | '/inspection/$id/review'
    | '/inspection/$id/sign'
    | '/inspection/setup/$propertyId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/inspections'
    | '/settings'
    | '/'
    | '/property/$id'
    | '/property/new'
    | '/inspection/$id/capture'
    | '/inspection/$id/compare'
    | '/inspection/$id/report'
    | '/inspection/$id/review'
    | '/inspection/$id/sign'
    | '/inspection/setup/$propertyId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/inspections'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/property/$id'
    | '/_authenticated/property/new'
    | '/_authenticated/inspection/$id/capture'
    | '/_authenticated/inspection/$id/compare'
    | '/_authenticated/inspection/$id/report'
    | '/_authenticated/inspection/$id/review'
    | '/_authenticated/inspection/$id/sign'
    | '/_authenticated/inspection/setup/$propertyId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property/new': {
      id: '/_authenticated/property/new'
      path: '/property/new'
      fullPath: '/property/new'
      preLoaderRoute: typeof AuthenticatedPropertyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property/$id': {
      id: '/_authenticated/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof AuthenticatedPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inspection/setup/$propertyId': {
      id: '/_authenticated/inspection/setup/$propertyId'
      path: '/inspection/setup/$propertyId'
      fullPath: '/inspection/setup/$propertyId'
      preLoaderRoute: typeof AuthenticatedInspectionSetupPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/sign': {
      id: '/_authenticated/inspection/$id/sign'
      path: '/inspection/$id/sign'
      fullPath: '/inspection/$id/sign'
      preLoaderRoute: typeof AuthenticatedInspectionIdSignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/review': {
      id: '/_authenticated/inspection/$id/review'
      path: '/inspection/$id/review'
      fullPath: '/inspection/$id/review'
      preLoaderRoute: typeof AuthenticatedInspectionIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/report': {
      id: '/_authenticated/inspection/$id/report'
      path: '/inspection/$id/report'
      fullPath: '/inspection/$id/report'
      preLoaderRoute: typeof AuthenticatedInspectionIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/compare': {
      id: '/_authenticated/inspection/$id/compare'
      path: '/inspection/$id/compare'
      fullPath: '/inspection/$id/compare'
      preLoaderRoute: typeof AuthenticatedInspectionIdCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/capture': {
      id: '/_authenticated/inspection/$id/capture'
      path: '/inspection/$id/capture'
      fullPath: '/inspection/$id/capture'
      preLoaderRoute: typeof AuthenticatedInspectionIdCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPropertyIdRoute: typeof AuthenticatedPropertyIdRoute
  AuthenticatedPropertyNewRoute: typeof AuthenticatedPropertyNewRoute
  AuthenticatedInspectionIdCaptureRoute: typeof AuthenticatedInspectionIdCaptureRoute
  AuthenticatedInspectionIdCompareRoute: typeof AuthenticatedInspectionIdCompareRoute
  AuthenticatedInspectionIdReportRoute: typeof AuthenticatedInspectionIdReportRoute
  AuthenticatedInspectionIdReviewRoute: typeof AuthenticatedInspectionIdReviewRoute
  AuthenticatedInspectionIdSignRoute: typeof AuthenticatedInspectionIdSignRoute
  AuthenticatedInspectionSetupPropertyIdRoute: typeof AuthenticatedInspectionSetupPropertyIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPropertyIdRoute: AuthenticatedPropertyIdRoute,
  AuthenticatedPropertyNewRoute: AuthenticatedPropertyNewRoute,
  AuthenticatedInspectionIdCaptureRoute: AuthenticatedInspectionIdCaptureRoute,
  AuthenticatedInspectionIdCompareRoute: AuthenticatedInspectionIdCompareRoute,
  AuthenticatedInspectionIdReportRoute: AuthenticatedInspectionIdReportRoute,
  AuthenticatedInspectionIdReviewRoute: AuthenticatedInspectionIdReviewRoute,
  AuthenticatedInspectionIdSignRoute: AuthenticatedInspectionIdSignRoute,
  AuthenticatedInspectionSetupPropertyIdRoute:
    AuthenticatedInspectionSetupPropertyIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
