/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedInspectionsRouteImport } from './routes/_authenticated/inspections'
import { Route as SignInspectionIdTokenRouteImport } from './routes/sign.$inspectionId.$token'
import { Route as AuthenticatedPropertyNewRouteImport } from './routes/_authenticated/property.new'
import { Route as AuthenticatedPropertyIdRouteImport } from './routes/_authenticated/property.$id'
import { Route as ApiPublicSignatureTokenTokenRouteImport } from './routes/api/public/signature-token.$token'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedListingIdReviewRouteImport } from './routes/_authenticated/listing.$id.review'
import { Route as AuthenticatedListingIdCaptureRouteImport } from './routes/_authenticated/listing.$id.capture'
import { Route as AuthenticatedInspectionSetupPropertyIdRouteImport } from './routes/_authenticated/inspection.setup.$propertyId'
import { Route as AuthenticatedInspectionIdSignRouteImport } from './routes/_authenticated/inspection.$id.sign'
import { Route as AuthenticatedInspectionIdReviewRouteImport } from './routes/_authenticated/inspection.$id.review'
import { Route as AuthenticatedInspectionIdReportRouteImport } from './routes/_authenticated/inspection.$id.report'
import { Route as AuthenticatedInspectionIdHhReportRouteImport } from './routes/_authenticated/inspection.$id.hh-report'
import { Route as AuthenticatedInspectionIdHealthyHomesRouteImport } from './routes/_authenticated/inspection.$id.healthy-homes'
import { Route as AuthenticatedInspectionIdCompareRouteImport } from './routes/_authenticated/inspection.$id.compare'
import { Route as AuthenticatedInspectionIdCaptureRouteImport } from './routes/_authenticated/inspection.$id.capture'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionsRoute =
  AuthenticatedInspectionsRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SignInspectionIdTokenRoute = SignInspectionIdTokenRouteImport.update({
  id: '/sign/$inspectionId/$token',
  path: '/sign/$inspectionId/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertyNewRoute =
  AuthenticatedPropertyNewRouteImport.update({
    id: '/property/new',
    path: '/property/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertyIdRoute = AuthenticatedPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSignatureTokenTokenRoute =
  ApiPublicSignatureTokenTokenRouteImport.update({
    id: '/api/public/signature-token/$token',
    path: '/api/public/signature-token/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedListingIdReviewRoute =
  AuthenticatedListingIdReviewRouteImport.update({
    id: '/listing/$id/review',
    path: '/listing/$id/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingIdCaptureRoute =
  AuthenticatedListingIdCaptureRouteImport.update({
    id: '/listing/$id/capture',
    path: '/listing/$id/capture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionSetupPropertyIdRoute =
  AuthenticatedInspectionSetupPropertyIdRouteImport.update({
    id: '/inspection/setup/$propertyId',
    path: '/inspection/setup/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdSignRoute =
  AuthenticatedInspectionIdSignRouteImport.update({
    id: '/inspection/$id/sign',
    path: '/inspection/$id/sign',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdReviewRoute =
  AuthenticatedInspectionIdReviewRouteImport.update({
    id: '/inspection/$id/review',
    path: '/inspection/$id/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdReportRoute =
  AuthenticatedInspectionIdReportRouteImport.update({
    id: '/inspection/$id/report',
    path: '/inspection/$id/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdHhReportRoute =
  AuthenticatedInspectionIdHhReportRouteImport.update({
    id: '/inspection/$id/hh-report',
    path: '/inspection/$id/hh-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdHealthyHomesRoute =
  AuthenticatedInspectionIdHealthyHomesRouteImport.update({
    id: '/inspection/$id/healthy-homes',
    path: '/inspection/$id/healthy-homes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdCompareRoute =
  AuthenticatedInspectionIdCompareRouteImport.update({
    id: '/inspection/$id/compare',
    path: '/inspection/$id/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspectionIdCaptureRoute =
  AuthenticatedInspectionIdCaptureRouteImport.update({
    id: '/inspection/$id/capture',
    path: '/inspection/$id/capture',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/sign/$inspectionId/$token': typeof SignInspectionIdTokenRoute
  '/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/inspection/$id/healthy-homes': typeof AuthenticatedInspectionIdHealthyHomesRoute
  '/inspection/$id/hh-report': typeof AuthenticatedInspectionIdHhReportRoute
  '/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/listing/$id/capture': typeof AuthenticatedListingIdCaptureRoute
  '/listing/$id/review': typeof AuthenticatedListingIdReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signature-token/$token': typeof ApiPublicSignatureTokenTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/inspections': typeof AuthenticatedInspectionsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
  '/property/new': typeof AuthenticatedPropertyNewRoute
  '/sign/$inspectionId/$token': typeof SignInspectionIdTokenRoute
  '/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/inspection/$id/healthy-homes': typeof AuthenticatedInspectionIdHealthyHomesRoute
  '/inspection/$id/hh-report': typeof AuthenticatedInspectionIdHhReportRoute
  '/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/listing/$id/capture': typeof AuthenticatedListingIdCaptureRoute
  '/listing/$id/review': typeof AuthenticatedListingIdReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signature-token/$token': typeof ApiPublicSignatureTokenTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/property/$id': typeof AuthenticatedPropertyIdRoute
  '/_authenticated/property/new': typeof AuthenticatedPropertyNewRoute
  '/sign/$inspectionId/$token': typeof SignInspectionIdTokenRoute
  '/_authenticated/inspection/$id/capture': typeof AuthenticatedInspectionIdCaptureRoute
  '/_authenticated/inspection/$id/compare': typeof AuthenticatedInspectionIdCompareRoute
  '/_authenticated/inspection/$id/healthy-homes': typeof AuthenticatedInspectionIdHealthyHomesRoute
  '/_authenticated/inspection/$id/hh-report': typeof AuthenticatedInspectionIdHhReportRoute
  '/_authenticated/inspection/$id/report': typeof AuthenticatedInspectionIdReportRoute
  '/_authenticated/inspection/$id/review': typeof AuthenticatedInspectionIdReviewRoute
  '/_authenticated/inspection/$id/sign': typeof AuthenticatedInspectionIdSignRoute
  '/_authenticated/inspection/setup/$propertyId': typeof AuthenticatedInspectionSetupPropertyIdRoute
  '/_authenticated/listing/$id/capture': typeof AuthenticatedListingIdCaptureRoute
  '/_authenticated/listing/$id/review': typeof AuthenticatedListingIdReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signature-token/$token': typeof ApiPublicSignatureTokenTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inspections'
    | '/maintenance'
    | '/settings'
    | '/team'
    | '/property/$id'
    | '/property/new'
    | '/sign/$inspectionId/$token'
    | '/inspection/$id/capture'
    | '/inspection/$id/compare'
    | '/inspection/$id/healthy-homes'
    | '/inspection/$id/hh-report'
    | '/inspection/$id/report'
    | '/inspection/$id/review'
    | '/inspection/$id/sign'
    | '/inspection/setup/$propertyId'
    | '/listing/$id/capture'
    | '/listing/$id/review'
    | '/api/public/payments/webhook'
    | '/api/public/signature-token/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/inspections'
    | '/maintenance'
    | '/settings'
    | '/team'
    | '/'
    | '/property/$id'
    | '/property/new'
    | '/sign/$inspectionId/$token'
    | '/inspection/$id/capture'
    | '/inspection/$id/compare'
    | '/inspection/$id/healthy-homes'
    | '/inspection/$id/hh-report'
    | '/inspection/$id/report'
    | '/inspection/$id/review'
    | '/inspection/$id/sign'
    | '/inspection/setup/$propertyId'
    | '/listing/$id/capture'
    | '/listing/$id/review'
    | '/api/public/payments/webhook'
    | '/api/public/signature-token/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/inspections'
    | '/_authenticated/maintenance'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/'
    | '/_authenticated/property/$id'
    | '/_authenticated/property/new'
    | '/sign/$inspectionId/$token'
    | '/_authenticated/inspection/$id/capture'
    | '/_authenticated/inspection/$id/compare'
    | '/_authenticated/inspection/$id/healthy-homes'
    | '/_authenticated/inspection/$id/hh-report'
    | '/_authenticated/inspection/$id/report'
    | '/_authenticated/inspection/$id/review'
    | '/_authenticated/inspection/$id/sign'
    | '/_authenticated/inspection/setup/$propertyId'
    | '/_authenticated/listing/$id/capture'
    | '/_authenticated/listing/$id/review'
    | '/api/public/payments/webhook'
    | '/api/public/signature-token/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignInspectionIdTokenRoute: typeof SignInspectionIdTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicSignatureTokenTokenRoute: typeof ApiPublicSignatureTokenTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/sign/$inspectionId/$token': {
      id: '/sign/$inspectionId/$token'
      path: '/sign/$inspectionId/$token'
      fullPath: '/sign/$inspectionId/$token'
      preLoaderRoute: typeof SignInspectionIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/property/new': {
      id: '/_authenticated/property/new'
      path: '/property/new'
      fullPath: '/property/new'
      preLoaderRoute: typeof AuthenticatedPropertyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property/$id': {
      id: '/_authenticated/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof AuthenticatedPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/signature-token/$token': {
      id: '/api/public/signature-token/$token'
      path: '/api/public/signature-token/$token'
      fullPath: '/api/public/signature-token/$token'
      preLoaderRoute: typeof ApiPublicSignatureTokenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/listing/$id/review': {
      id: '/_authenticated/listing/$id/review'
      path: '/listing/$id/review'
      fullPath: '/listing/$id/review'
      preLoaderRoute: typeof AuthenticatedListingIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing/$id/capture': {
      id: '/_authenticated/listing/$id/capture'
      path: '/listing/$id/capture'
      fullPath: '/listing/$id/capture'
      preLoaderRoute: typeof AuthenticatedListingIdCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/setup/$propertyId': {
      id: '/_authenticated/inspection/setup/$propertyId'
      path: '/inspection/setup/$propertyId'
      fullPath: '/inspection/setup/$propertyId'
      preLoaderRoute: typeof AuthenticatedInspectionSetupPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/sign': {
      id: '/_authenticated/inspection/$id/sign'
      path: '/inspection/$id/sign'
      fullPath: '/inspection/$id/sign'
      preLoaderRoute: typeof AuthenticatedInspectionIdSignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/review': {
      id: '/_authenticated/inspection/$id/review'
      path: '/inspection/$id/review'
      fullPath: '/inspection/$id/review'
      preLoaderRoute: typeof AuthenticatedInspectionIdReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/report': {
      id: '/_authenticated/inspection/$id/report'
      path: '/inspection/$id/report'
      fullPath: '/inspection/$id/report'
      preLoaderRoute: typeof AuthenticatedInspectionIdReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/hh-report': {
      id: '/_authenticated/inspection/$id/hh-report'
      path: '/inspection/$id/hh-report'
      fullPath: '/inspection/$id/hh-report'
      preLoaderRoute: typeof AuthenticatedInspectionIdHhReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/healthy-homes': {
      id: '/_authenticated/inspection/$id/healthy-homes'
      path: '/inspection/$id/healthy-homes'
      fullPath: '/inspection/$id/healthy-homes'
      preLoaderRoute: typeof AuthenticatedInspectionIdHealthyHomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/compare': {
      id: '/_authenticated/inspection/$id/compare'
      path: '/inspection/$id/compare'
      fullPath: '/inspection/$id/compare'
      preLoaderRoute: typeof AuthenticatedInspectionIdCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspection/$id/capture': {
      id: '/_authenticated/inspection/$id/capture'
      path: '/inspection/$id/capture'
      fullPath: '/inspection/$id/capture'
      preLoaderRoute: typeof AuthenticatedInspectionIdCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInspectionsRoute: typeof AuthenticatedInspectionsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPropertyIdRoute: typeof AuthenticatedPropertyIdRoute
  AuthenticatedPropertyNewRoute: typeof AuthenticatedPropertyNewRoute
  AuthenticatedInspectionIdCaptureRoute: typeof AuthenticatedInspectionIdCaptureRoute
  AuthenticatedInspectionIdCompareRoute: typeof AuthenticatedInspectionIdCompareRoute
  AuthenticatedInspectionIdHealthyHomesRoute: typeof AuthenticatedInspectionIdHealthyHomesRoute
  AuthenticatedInspectionIdHhReportRoute: typeof AuthenticatedInspectionIdHhReportRoute
  AuthenticatedInspectionIdReportRoute: typeof AuthenticatedInspectionIdReportRoute
  AuthenticatedInspectionIdReviewRoute: typeof AuthenticatedInspectionIdReviewRoute
  AuthenticatedInspectionIdSignRoute: typeof AuthenticatedInspectionIdSignRoute
  AuthenticatedInspectionSetupPropertyIdRoute: typeof AuthenticatedInspectionSetupPropertyIdRoute
  AuthenticatedListingIdCaptureRoute: typeof AuthenticatedListingIdCaptureRoute
  AuthenticatedListingIdReviewRoute: typeof AuthenticatedListingIdReviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInspectionsRoute: AuthenticatedInspectionsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPropertyIdRoute: AuthenticatedPropertyIdRoute,
  AuthenticatedPropertyNewRoute: AuthenticatedPropertyNewRoute,
  AuthenticatedInspectionIdCaptureRoute: AuthenticatedInspectionIdCaptureRoute,
  AuthenticatedInspectionIdCompareRoute: AuthenticatedInspectionIdCompareRoute,
  AuthenticatedInspectionIdHealthyHomesRoute:
    AuthenticatedInspectionIdHealthyHomesRoute,
  AuthenticatedInspectionIdHhReportRoute:
    AuthenticatedInspectionIdHhReportRoute,
  AuthenticatedInspectionIdReportRoute: AuthenticatedInspectionIdReportRoute,
  AuthenticatedInspectionIdReviewRoute: AuthenticatedInspectionIdReviewRoute,
  AuthenticatedInspectionIdSignRoute: AuthenticatedInspectionIdSignRoute,
  AuthenticatedInspectionSetupPropertyIdRoute:
    AuthenticatedInspectionSetupPropertyIdRoute,
  AuthenticatedListingIdCaptureRoute: AuthenticatedListingIdCaptureRoute,
  AuthenticatedListingIdReviewRoute: AuthenticatedListingIdReviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SignInspectionIdTokenRoute: SignInspectionIdTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicSignatureTokenTokenRoute: ApiPublicSignatureTokenTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
